//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurLibrary.Models
{
    using Annotation;
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class book_record
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public book_record()
        {
            this.book_issue = new HashSet<book_issue>();
        }



        [FieldAttribute(AutoGenerated = true, Required = true, FieldType = AttributeConstant.TYPE_ID_STR_NUMB, FixSize = 9)]
        public string id { get; set; }
        [FieldAttribute(Required = true, FieldType = AttributeConstant.TYPE_TEXTBOX)]
        public string book_code { get; set; }
        [FieldAttribute(Required = true, FieldType = AttributeConstant.TYPE_SEARCHLIST,
            FieldName = "Book", ClassReference = "book",
            ClassAttributeConverter = "title", AttrToDisplay = new string[] { "title", "author>name" })]
        public string book_id { get; set; }
        [FieldAttribute(Required = false, FieldType = AttributeConstant.TYPE_TEXTAREA)]
        public string additional_info { get; set; }
        [FieldAttribute(Required = true, FieldType = AttributeConstant.TYPE_DROPDOWN, DropDownValues = new object[] { 0, 1 }, DropDownItemName = new object[] { "unavailable", "available" })]
        public Nullable<short> available { get; set; }

        public virtual book book { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<book_issue> book_issue { get; set; }
    }
}
