//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurLibrary.Models
{
    using Annotation;
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class issue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public issue()
        {
            this.book_issue = new HashSet<book_issue>();
        }
        [FieldAttribute(AutoGenerated = true, Required = true, FieldType = AttributeConstant.TYPE_ID_STR_NUMB)]

        public string id { get; set; }
        [FieldAttribute(FieldType = AttributeConstant.TYPE_READONLY)]


        public System.DateTime date { get; set; }
        [FieldAttribute(FieldType = AttributeConstant.TYPE_READONLY)]

        public string user_id { get; set; }
        [FieldAttribute(FieldType = AttributeConstant.TYPE_READONLY)]

        public string student_id { get; set; }
        [FieldAttribute(FieldType = AttributeConstant.TYPE_READONLY)]

        public string addtional_info { get; set; }
        [FieldAttribute(FieldType = AttributeConstant.TYPE_READONLY)]

        public string type { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<book_issue> book_issue { get; set; }
        public virtual student student { get; set; }
        public virtual user user { get; set; }
    }
}
